version: 0.2
phases:
   pre_build:
     commands:
        - echo setting docker connection  in ecr
        - aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 763768204702.dkr.ecr.ap-south-1.amazonaws.com
        - REPOSITORY_URI=763768204702.dkr.ecr.ap-south-1.amazonaws.com/demorornginx
        - REPOSITORY_URI_NGINX=763768204702.dkr.ecr.ap-south-1.amazonaws.com/demonginx
  
   build: 
     commands:
        - echo building the docker file
        - docker build -t ror .
        - echo done with building ror
        - cd ./nginx
        - docker build -t nginx .
        - echo done wth building nginx

   post_build:
     commands:
        - echo tagging ror image with ecr
        - docker tag ror:latest $REPOSITORY_URI:latest
        - echo pushing ror image to ecr
        - docker push $REPOSITORY_URI:latest
        - echo pushed image to ecr
        - echo tagging nginx image with ecr
        - docker tag nginx:latest $REPOSITORY_URI_NGINX:latest
        - echo pushing ngnix image to ecr
        - docker push $REPOSITORY_URI_NGINX:latest
        - printf '[{"name":"ror","imageUri":"%s"}]' 763768204702.dkr.ecr.ap-south-1.amazonaws.com/demorornginx:latest > imagedefinitions.json
        - printf '[{"name":"ror","imageUri":"%s"}]' 763768204702.dkr.ecr.ap-south-1.amazonaws.com/demonginx:latest >> imagedefinitions.json
artifacts:
     files: imagedefinitions.json



   

                 
