version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 763768204702.dkr.ecr.ap-south-1.amazonaws.com
      - REPOSITORY_URI=763768204702.dkr.ecr.ap-south-1.amazonaws.com/demorornginx
      - REPOSITORY_URI_NGINX=763768204702.dkr.ecr.ap-south-1.amazonaws.com/demonginx

  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t $REPOSITORY_URI:latest .
      - docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:latest
      - docker build -t $REPOSITORY_URI_NGINX:latest .
      - docker tag $REPOSITORY_URI_NGINX:latest $REPOSITORY_URI_NGINX:latest
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker ror image...
      - docker push $REPOSITORY_URI:latest
      - echo push nginx image...
      - docker push $REPOSITORY_URI_NGINX:latest
      - echo Writing image definitions file...
      - printf '[{"name":"ror","imageUri":"%s"}]\n[{"name":"nginx","imageUri":"%s"}]' $REPOSITORY_URI:latest $REPOSITORY_URI_NGINX:latest > imagedefinitions.json
artifacts:
    files: imagedefinitions.json
