version: 0.2
phases:
   pre_build:
     commands:
        - echo setting docker connection  in ecr
        - aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 763768204702.dkr.ecr.ap-south-1.amazonaws.com
        - REPOSITORY_URI=763768204702.dkr.ecr.ap-south-1.amazonaws.com/demorornginx
        - IMAGE_TAG=build-$(echo $CODEBUILD_BUILD_ID | awk -F":" '{print $2}')
   build: 
     commands:
        - echo building the docker file
        - docker build -t ror .
        - echo done with building ror
        - cd ./nginx
        - docker build -t nginx .
        - echo done wth building nginx

   post_build:
     commands:
        - echo tagging ror image with ecr
        - docker tag ror:latest $REPOSITORY_URI:$IMAGE_TAG
        - docker tag ror:latest $REPOSITORY_URI:latest
        - echo pushing ror image to ecr
        - docker push $REPOSITORY_URI:latest
        - docker push $REPOSITORY_URI:$IMAGE_TAG
        - echo pushed image to ecr
        - echo tagging nginx with ecr
        - docker tag nginx:latest $REPOSITORY_URI:$IMAGE_TAG
        - docker tag nginx:latest $REPOSITORY_URI:latest
        - echo pushing nginx image to ecr
        - docker push $REPOSITORY_URI:latest
        - docker push $REPOSITORY_URI:$IMAGE_TAG


        

   

                 
