name: Build and Deploy to EC2

on:
  push:
    branches:
      - master
  workflow_dispatch:    

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        run: |
         echo "${{ secrets.DOCKERHUB_TOKEN }}"
         echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin
  

      - name: Build Docker image
        run: |
          SHORT_SHA=$(echo "${{ github.sha }}" | cut -c1-9)
          echo "SHORT_SHA=$SHORT_SHA" >> $GITHUB_ENV
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/nginx:$SHORT_SHA -f ./nginx/Dockerfile .
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/nginx:$SHORT_SHA


  # deploy:
  #   runs-on: ubuntu-latest    
  #   needs: build-and-push
  #   steps:

      - name: Log in to Docker Hub
        run: |
         echo "${{ secrets.DOCKERHUB_TOKEN }}"
         echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin
      - name: Copy SSH key
        run: |
          echo "${{ secrets.EC2_SSH_KEY }}" > key.pem
          chmod 600 key.pem
      - name: Deploy to EC2 via SSH
        run: |
          SHORT_SHA=$(echo "${{ github.sha }}" | cut -c1-9)
          ssh -o StrictHostKeyChecking=no -i key.pem ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << EOF
          set -xe
          cd ~
          SHORT_SHA=${{ env.SHORT_SHA }}
          DOCKERHUB_USERNAME=${{ secrets.DOCKERHUB_USERNAME }}

          if [ -d "devopsrorbilling" ]; then
           sudo bash -c '
            cd devopsrorbilling
            git pull origin master
           '
          else
           sudo git clone https://github.com/naveen2112/devopsrorbilling.git
           sudo bash -c '
            cd devopsrorbilling
           '
          fi

          # Replace the image tag with git SHA
          sudo ls -la
          cd devopsrorbilling
          sudo bash -c "sed -i 's|naveen2112/nginx:*|naveen2112/nginx:$SHORT_SHA|' docker-compose.yml"
          
          cat docker-compose.yml

          # # Pull latest docker image
          # Pull and run
          sudo docker pull \$DOCKERHUB_USERNAME/nginx:\$SHORT_SHA
          sudo docker-compose up -d
          EOF

